version: '3.8'

services:
  order-service:
    build:
      context: .
      dockerfile: deployments/Dockerfile.order
    ports:
      - "8081:8080"
    environment:
      - DB_URL=${DB_URL}
      - MQ_URL=${MQ_URL}
    networks:
      - logistic-network

  payment-service:
    build:
      context: .
      dockerfile: deployments/Dockerfile.payment
    ports:
      - "8082:8080"
    environment:
      - DB_URL=${DB_URL}
      - MQ_URL=${MQ_URL}
    networks:
      - logistic-network

  inventory-service:
    build:
      context: .
      dockerfile: deployments/Dockerfile.inventory
    ports:
      - "8083:8080"
    environment:
      - DB_URL=${DB_URL}
      - MQ_URL=${MQ_URL}
    networks:
      - logistic-network

  notification-service:
    build:
      context: .
      dockerfile: deployments/Dockerfile.notification
    ports:
      - "8084:8080"
    environment:
      - DB_URL=${DB_URL}
      - MQ_URL=${MQ_URL}
    networks:
      - logistic-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - logistic-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: logistic_db
    ports:
      - "5432:5432"
    networks:
      - logistic-network

networks:
  logistic-network:
    driver: bridge
